name: rainbow
description: none

publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.3
  flutter_riverpod: ^2.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: font/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: font/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: font/JetBrainsMono-Light.ttf
          weight: 300
        - asset: font/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: font/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: font/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: font/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: font/JetBrainsMono-ExtraBold.ttf
          weight: 800